package edu.ucsc.dbtune.viz;

import java.util.ArrayList;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

import edu.ucsc.dbtune.advisor.WorkloadObserverAdvisor;

/**
 * A visualizer that aggregates {@link SwingVisualizer SwingVisualizer's} in a tabbed interface.
 *
 * @author Ivo Jimenez
 */
public class TabbedSwingVisualizer extends SwingVisualizer
{
    static final long serialVersionUID = 0;

    private javax.swing.JTabbedPane jTabbedPane1;

    private List<SwingVisualizer> swingVisualizers;

    /**
     * Creates new form Window
     */
    public TabbedSwingVisualizer(WorkloadObserverAdvisor advisor)
    {
        super(advisor);

        initComponents();

        swingVisualizers = new ArrayList<SwingVisualizer>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents()
    {
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                    jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(
            layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                    jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE));

        pack();

        setSize(1024, 512);
        setLocation(512, 24);

        ImageIcon img = new ImageIcon("resources/images/ucsc-seal.jpg");
        setIconImage(img.getImage());

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     */
    public void add(String name, SwingVisualizer visualizer)
    {
        jTabbedPane1.addTab(name, visualizer.getContentPane());
        swingVisualizers.add(visualizer);
    }

    public List<SwingVisualizer> getVisualizers()
    {
        return swingVisualizers;
    }

    /**
     */
    @Override
    public void updateContent() throws Exception
    {
        for (SwingVisualizer vis : swingVisualizers) {
            vis.updateContent();
        }
    }
}
