-- TPC TPC-H Parameter Substitution (Version 2.3.1 build 2)
-- using 638592433 as a seed to the RNG
-- ?SECTION Q14
-- TPC-H/TPC-R Promotion Effect Query (Q14)
-- Stream 0, Query 14
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- determine what % of revenue in a given year & month was derived
-- from promotional parts shipped in a given month.
-- ------------------------------------------------------------------
 
select
      cast( (100.00 * sum(case
            when p_type like 'PROMO%'
                  then l_extendedprice * (1 - l_discount)
            else 0
      end) / sum(l_extendedprice * (1 - l_discount)) 
      ) as numeric(18,3)) as promo_revenue
from
      tpch.lineitem,
      tpch.part
where
      l_partkey = p_partkey
      and l_shipdate >= date '1996-01-01'
      and l_shipdate < date '1996-01-01' + interval '1' month;

-- ?SECTION Q2
-- TPC-H/TPC-R Minimum Cost Supplier Query (Q2)
-- Stream 0, Query 2
-- Database -- <catalog>.<schema>

-- -------------------------------------------------------------------
-- For a given region, find the supplier who can supply a part
-- type and size at least cost.
-- -------------------------------------------------------------------
 
select [first 100]
      cast(s_acctbal as numeric(18,2)),
      s_name,
      n_name,
      p_partkey,
      p_mfgr,
      s_address,
      s_phone,
      s_comment
from
      tpch.part,
      tpch.supplier,
      tpch.partsupp,
      tpch.nation,
      tpch.region
where
      p_partkey = ps_partkey
      and s_suppkey = ps_suppkey
      and p_size = 5
      and p_type like '%NICKEL'
      and s_nationkey = n_nationkey
      and n_regionkey = r_regionkey
      and r_name = 'AMERICA'
      and ps_supplycost = (
            select
                  min(ps_supplycost)
            from
                  tpch.partsupp,
                  tpch.supplier,
                  tpch.nation,
                  tpch.region
            where
                  p_partkey = ps_partkey
                  and s_suppkey = ps_suppkey
                  and s_nationkey = n_nationkey
                  and n_regionkey = r_regionkey
                  and r_name = 'AMERICA'
      )
order by
      s_acctbal desc,
      n_name,
      s_name,
      p_partkey;


-- ?SECTION Q9
-- TPC-H/TPC-R Product Type Profit Measure Query (Q9)
-- Stream 0, Query 9
-- Database -- <catalog>.<schema>

-- --------------------------------------------------------------------
-- determine how much profit is made on a line of
-- parts, broken out by supplier nation and year.
-- --------------------------------------------------------------------
 
select
      nation,
      o_year,
      cast(sum(amount) as numeric(18,2)) as sum_profit
from
      (
            select
                  n_name as nation,
                  extract(year from tpch.o_orderdate) as o_year,
                  l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount
            from
                  tpch.part,
                  tpch.supplier,
                  tpch.lineitem,
                  tpch.partsupp,
                  tpch.orders,
                  tpch.nation
            where
                  s_suppkey = l_suppkey
                  and ps_suppkey = l_suppkey
                  and ps_partkey = l_partkey
                  and p_partkey = l_partkey
                  and o_orderkey = l_orderkey
                  and s_nationkey = n_nationkey
                  and p_name like '%maroon%'
      ) as profit
group by
      nation,
      o_year
order by
      nation,
      o_year desc;


-- ?SECTION Q6
-- TPC-H/TPC-R Forecasting Revenue Change Query (Q6)
-- Stream 0, Query 6
-- Database -- <catalog>.<schema>

-- ----------------------------------------------------------------------
-- consider all lineitems shipped in a given year with discounts
-- within a specified range.  Lists the amount by which the total revenue
-- would have increased if these discounts had been eliminated.
-- ----------------------------------------------------------------------
 
select
      cast(sum(l_extendedprice*l_discount) as numeric(18,2)) as revenue
from
      tpch.lineitem
where
      l_shipdate >= date '1997-01-01'
      and l_shipdate < date '1997-01-01' + interval '1' year
      and l_discount between 0.03 - 0.01 and 0.03 + 0.01
      and l_quantity < 25;

-- ?SECTION Q8
-- TPC-H/TPC-R National Market Share Query (Q8)
-- Stream 0, Query 8
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- determines how the market share of a given nation in a given
-- region has changed over two years for a given part type. Market
-- share is the fraction of the revenue from products of a given type
-- that was generated by suppliers from the given nation.
-- ------------------------------------------------------------------
 
select
      o_year,
      cast(sum(case
            when nation = 'JORDAN' then volume
            else 0
      end) / sum(volume) as numeric(18,3)) as mkt_share
from
      (
            select
                  extract(year from tpch.o_orderdate) as o_year,
                  l_extendedprice * (1 - l_discount) as volume,
                  n2.n_name as nation
            from
                  tpch.part,
                  tpch.supplier,
                  tpch.lineitem,
                  tpch.orders,
                  tpch.customer,
                  tpch.nation n1,
                  tpch.nation n2,
                  tpch.region
            where
                  p_partkey = l_partkey
                  and s_suppkey = l_suppkey
                  and l_orderkey = o_orderkey
                  and o_custkey = c_custkey
                  and c_nationkey = n1.n_nationkey
                  and n1.n_regionkey = r_regionkey
                  and r_name = 'MIDDLE EAST'
                  and s_nationkey = n2.n_nationkey
                  and o_orderdate between date '1995-01-01' and date '1996-12-31'
                  and p_type = 'LARGE ANODIZED COPPER'
      ) as all_nations
group by
      o_year
order by
      o_year;


-- ?SECTION Q13
-- TPC-H/TPC-R Customer Distribution Query (Q13)
-- Stream 0, Query 13
-- Database -- <catalog>.<schema>

-- ---------------------------------------------------------------------
-- determines the distribution of customers by the number of orders
-- they have made, including customers who have no record of orders,
-- past or present. Counts and reports how many customers have no
-- orders, how many have 1, 2, 3, etc. A check is made to ensure that
-- the orders counted do not fall into one of several special categories
-- of orders. Special categories are identified in the order comment
-- column by looking for a particular pattern.
-- ---------------------------------------------------------------------
 
select
      c_count,
      count(*) as custdist
from
      (
            select
                  c_custkey,
                  count(o_orderkey)
            from
                  tpch.customer left outer join orders on
                        c_custkey = o_custkey
                        and o_comment not like '%special%accounts%'
            group by
                  c_custkey
      ) as c_orders (c_custkey, c_count)
group by
      c_count
order by
      custdist desc,
      c_count desc;


-- ?SECTION Q3
-- TPC-H/TPC-R Shipping Priority Query (Q3)
-- Stream 0, Query 3
-- Database -- <catalog>.<schema>

-- -------------------------------------------------------------------
-- retrieves the shipping priority and potential revenue of orders
-- having the largest revenue among those that had not been shipped
-- as of a given date.
-- -------------------------------------------------------------------
 
select [first 10]
      l_orderkey,
      cast(sum(l_extendedprice*(1-l_discount)) as numeric(18,2)) as revenue,
      o_orderdate,
      o_shippriority
from
      tpch.customer,
      tpch.orders,
      tpch.lineitem
where
      c_mktsegment = 'HOUSEHOLD'
      and c_custkey = o_custkey
      and l_orderkey = o_orderkey
      and o_orderdate < date '1995-03-12'
      and l_shipdate > date '1995-03-12'
group by
      l_orderkey,
      o_orderdate,
      o_shippriority
order by
      revenue desc,
      o_orderdate;


-- ?SECTION Q16
-- TPC-H/TPC-R Parts/Supplier Relationship Query (Q16)
-- Stream 0, Query 16
-- Database -- <catalog>.<schema>

-- -----------------------------------------------------------------
-- count the number of suppliers who can supply parts that satisfy a
-- particular customer's requirements
-- -----------------------------------------------------------------
 
select [last 0]
      p_brand,
      p_type,
      p_size,
      count(distinct ps_suppkey) as supplier_cnt
from
      tpch.partsupp,
      tpch.part
where
      p_partkey = ps_partkey
      and p_brand <> 'Brand#13'
      and p_type not like 'SMALL PLATED%'
      and p_size in (22, 14, 8, 18, 49, 1, 33, 6)
      and ps_suppkey not in (
            select
                  s_suppkey
            from
                  tpch.supplier
            where
                  s_comment like '%Customer%Complaints%'
      )
group by
      p_brand,
      p_type,
      p_size
order by
      supplier_cnt desc,
      p_brand,
      p_type,
      p_size;

-- ?SECTION Q4
-- TPC-H/TPC-R Order Priority Checking Query (Q4)
-- Stream 0, Query 4
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- counts the number of orders ordered in a given quarter of a given
-- year in which at least at least one lineitem was received later
-- than its committed date. The query lists the count of such orders
-- for each order priority sorted in ascending priority order.
-- ------------------------------------------------------------------
 
select
      o_orderpriority,
      count(*) as order_count
from
      tpch.orders
where
      o_orderdate >= date '1994-10-01'
      and o_orderdate < date '1994-10-01' + interval '3' month
      and exists (
            select
                  *
            from
                  tpch.lineitem
            where
                  l_orderkey = o_orderkey
                  and l_commitdate < l_receiptdate
      )
group by
      o_orderpriority
order by
      o_orderpriority;

-- ?SECTION Q11
-- TPC-H/TPC-R Important Stock Identification Query (Q11)
-- Stream 0, Query 11
-- Database -- <catalog>.<schema>

-- -------------------------------------------------------------------
-- find, for suppliers in a given nation, all the parts that represent
-- a significant percentage of the total value of all available parts
-- -------------------------------------------------------------------
 
select [last 0]
      ps_partkey,
      cast(sum(ps_supplycost * ps_availqty) as numeric(18,2)) as valuea
from
      tpch.partsupp,
      tpch.supplier,
      tpch.nation
where
      ps_suppkey = s_suppkey
      and s_nationkey = n_nationkey
      and n_name = 'ROMANIA'
group by
      ps_partkey having
            sum(ps_supplycost * ps_availqty) > (
                  select
                        sum(ps_supplycost * ps_availqty) * 0.0000005000
                  from
                        tpch.partsupp,
                        tpch.supplier,
                        tpch.nation
                  where
                        ps_suppkey = s_suppkey
                        and s_nationkey = n_nationkey
                        and n_name = 'ROMANIA'
            )
order by
      valuea desc;

-- ?SECTION Q15
-- TPC-H/TPC-R Top Supplier Query (Q15)
-- Stream 0, Query 15
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- determines supplier who contributed most to the overall revenue   
-- for parts shipped during a given quarter of a given year.         
-- ------------------------------------------------------------------

-- Fix -- cast predicate and subquery to ensure match
-- Fix -- replaced view with in-line SQL
 
select
      s_suppkey,
      s_name,
      s_address,
      s_phone,
      cast(total_revenue as numeric(18,2))
from
      tpch.supplier,
      (
      select
            l_suppkey,
            sum(l_extendedprice * (1 - l_discount))
      from
            tpch.lineitem
      where
            l_shipdate >= date '1994-02-01'
            and l_shipdate < date '1994-02-01' + interval '3' month
      group by
            l_suppkey
      ) as v(supplier_no, total_revenue)
where
      s_suppkey = supplier_no
      and cast((total_revenue + 0.005) as numeric(18,2)) = (
            select
                  cast((max(total_revenue) + 0.005) as numeric(18,2))
            from
            (
            select
                  l_suppkey,
                  sum(l_extendedprice * (1 - l_discount))
            from
                  tpch.lineitem
            where
                  l_shipdate >= date '1994-02-01'
                  and l_shipdate < date '1994-02-01' + interval '3' month
            group by
                  l_suppkey
            ) as v1(supplier_no, total_revenue)
      )
order by
      s_suppkey;


-- ?SECTION Q1
-- TPC-H/TPC-R Pricing Summary Report Query (Q1)
-- Stream 0, Query 1
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- Summary pricing report for all lineitems as of a given ship date.
-- Expected to scan 95-97% of table.
-- ------------------------------------------------------------------
 
select
      l_returnflag,
      l_linestatus,
      cast(sum(l_quantity)                                   as numeric(18,2)) as sum_qty,
      cast(sum(l_extendedprice)                              as numeric(18,2)) as sum_base_price,
      cast(sum(l_extendedprice * (1 - l_discount))           as numeric(18,2)) as sum_disc_price,
      cast(sum(l_extendedprice * (1 - l_discount)*(1+l_tax)) as numeric(18,2)) as sum_charge,
      cast(avg(l_quantity)                                   as numeric(18,3)) as avg_qty,
      cast(avg(l_extendedprice)                              as numeric(18,3)) as avg_price,
      cast(avg(l_discount)                                   as numeric(18,3)) as avg_disc,
      count(*) as count_order
from
      tpch.lineitem
where
      l_shipdate <= date '1998-12-01' - interval '69' day (3)
group by
      l_returnflag,
      l_linestatus
order by
      l_returnflag,
      l_linestatus;


-- ?SECTION Q10
-- TPC-H/TPC-R Returned Item Reporting Query (Q10)
-- Stream 0, Query 10
-- Database -- <catalog>.<schema>

-------------------------------------------------------------------
-- identifies customers who might be having problems with the parts
-- that are shipped to them (returning them)
-------------------------------------------------------------------
 
select [first 20]
      c_custkey,
      c_name,
      cast(sum(l_extendedprice * (1 - l_discount)) as numeric(18,2)) as revenue,
      cast(c_acctbal as numeric(18,2)),
      n_name,
      c_address,
      c_phone,
      c_comment
from
      tpch.customer,
      tpch.orders,
      tpch.lineitem,
      tpch.nation
where
      c_custkey = o_custkey
      and l_orderkey = o_orderkey
      and o_orderdate >= date '1994-07-01'
      and o_orderdate < date '1994-07-01' + interval '3' month
      and l_returnflag = 'R'
      and c_nationkey = n_nationkey
group by
      c_custkey,
      c_name,
      c_acctbal,
      c_phone,
      n_name,
      c_address,
      c_comment
order by
      revenue desc;

-- ?SECTION Q19
-- TPC-H/TPC-R Discounted Revenue Query (Q19)
-- Stream 0, Query 19
-- Database -- <catalog>.<schema>

-- ----------------------------------------------------------------
-- find gross discounted revenue for all orders for three different
-- types of parts that were shipped by air or delivered in person
-- ----------------------------------------------------------------
 
select
      cast (sum(l_extendedprice* (1 - l_discount)) as numeric(18,4)) as revenue
from
      tpch.lineitem,
      tpch.part
where
      (
            p_partkey = l_partkey
            and p_brand = 'Brand#11'
            and p_container in ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')
            and l_quantity >= 1 and l_quantity <= 1 + 10
            and p_size between 1 and 5
            and l_shipmode in ('AIR', 'AIR REG')
            and l_shipinstruct = 'DELIVER IN PERSON'
      )
      or
      (
            p_partkey = l_partkey
            and p_brand = 'Brand#22'
            and p_container in ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK')
            and l_quantity >= 13 and l_quantity <= 13 + 10
            and p_size between 1 and 10
            and l_shipmode in ('AIR', 'AIR REG')
            and l_shipinstruct = 'DELIVER IN PERSON'
      )
      or
      (
            p_partkey = l_partkey
            and p_brand = 'Brand#52'
            and p_container in ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG')
            and l_quantity >= 21 and l_quantity <= 21 + 10
            and p_size between 1 and 15
            and l_shipmode in ('AIR', 'AIR REG')
            and l_shipinstruct = 'DELIVER IN PERSON'
      );

-- ?SECTION Q5
-- TPC-H/TPC-R Local Supplier Volume Query (Q5)
-- Stream 0, Query 5
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- For each nation in a region, list the revenue resulting from
-- lineitem transactions in which the customer ordering parts and the
-- supplier filling them were both within that nation. Only parts
-- ordered in a given year are considered.  Ordered by revenue.
-- ------------------------------------------------------------------
 
select
      n_name,
      cast(sum(l_extendedprice * (1 - l_discount)) as numeric(18,2)) as revenue
from
      tpch.customer,
      tpch.orders,
      tpch.lineitem,
      tpch.supplier,
      tpch.nation,
      tpch.region
where
      c_custkey = o_custkey
      and l_orderkey = o_orderkey
      and l_suppkey = s_suppkey
      and c_nationkey = s_nationkey
      and s_nationkey = n_nationkey
      and n_regionkey = r_regionkey
      and r_name = 'ASIA'
      and o_orderdate >= date '1997-01-01'
      and o_orderdate < date '1997-01-01' + interval '1' year
group by
      n_name
order by
      revenue desc;

-- ?SECTION Q7
-- TPC-H/TPC-R Volume Shipping Query (Q7)
-- Stream 0, Query 7
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- for two given nations, find the gross discounted revenues derived
-- from lineitems in which parts were shipped from a supplier in
-- either nation to a customer in the other nation during 1995 and
-- 1996.  Order by supplier nation, customer nation, and year.
-- ------------------------------------------------------------------
 
select
      supp_nation,
      cust_nation,
      l_year,
      cast(sum(volume) as numeric(18,2)) as revenue
from
      (
            select
                  n1.n_name as supp_nation,
                  n2.n_name as cust_nation,
                  extract(year from tpch.l_shipdate) as l_year,
                  l_extendedprice * (1 - l_discount) as volume
            from
                  tpch.supplier,
                  tpch.lineitem,
                  tpch.orders,
                  tpch.customer,
                  tpch.nation n1,
                  tpch.nation n2
            where
                  s_suppkey = l_suppkey
                  and o_orderkey = l_orderkey
                  and c_custkey = o_custkey
                  and s_nationkey = n1.n_nationkey
                  and c_nationkey = n2.n_nationkey
                  and (
                        (n1.n_name = 'ETHIOPIA' and n2.n_name = 'JORDAN')
                        or (n1.n_name = 'JORDAN' and n2.n_name = 'ETHIOPIA')
                  )
                  and l_shipdate between date '1995-01-01' and date '1996-12-31'
      ) as shipping
group by
      supp_nation,
      cust_nation,
      l_year
order by
      supp_nation,
      cust_nation,
      l_year;

-- ?SECTION Q12
-- TPC-H/TPC-R Shipping Modes and Order Priority Query (Q12)
-- Stream 0, Query 12
-- Database -- <catalog>.<schema>

-- -------------------------------------------------------------------
-- determines whether less expensive shipping modes are negatively
-- affecting critical priority orders
-- -------------------------------------------------------------------
 
select
      l_shipmode,
      sum(case
            when o_orderpriority = '1-URGENT'
                  or o_orderpriority = '2-HIGH'
                  then 1
            else 0
      end) as high_line_count,
      sum(case
            when o_orderpriority <> '1-URGENT'
                  and o_orderpriority <> '2-HIGH'
                  then 1
            else 0
      end) as low_line_count
from
      tpch.orders,
      tpch.lineitem
where
      o_orderkey = l_orderkey
      and l_shipmode in ('REG AIR', 'AIR')
      and l_commitdate < l_receiptdate
      and l_shipdate < l_commitdate
      and l_receiptdate >= date '1995-01-01'
      and l_receiptdate < date '1995-01-01' + interval '1' year
group by
      l_shipmode
order by
      l_shipmode;

 
-- TPC TPC-H Parameter Substitution (Version 2.3.1 build 2)
-- using default substitutions
-- ?SECTION Q1
-- TPC-H/TPC-R Pricing Summary Report Query (Q1)
-- Stream 0, Query 1
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- Summary pricing report for all lineitems as of a given ship date.
-- Expected to scan 95-97% of table.
-- ------------------------------------------------------------------
 
select
      l_returnflag,
      l_linestatus,
      cast(sum(l_quantity)                                   as numeric(18,2)) as sum_qty,
      cast(sum(l_extendedprice)                              as numeric(18,2)) as sum_base_price,
      cast(sum(l_extendedprice * (1 - l_discount))           as numeric(18,2)) as sum_disc_price,
      cast(sum(l_extendedprice * (1 - l_discount)*(1+l_tax)) as numeric(18,2)) as sum_charge,
      cast(avg(l_quantity)                                   as numeric(18,3)) as avg_qty,
      cast(avg(l_extendedprice)                              as numeric(18,3)) as avg_price,
      cast(avg(l_discount)                                   as numeric(18,3)) as avg_disc,
      count(*) as count_order
from
      tpch.lineitem
where
      l_shipdate <= date '1998-12-01' - interval '90' day (3)
group by
      l_returnflag,
      l_linestatus
order by
      l_returnflag,
      l_linestatus;


-- ?SECTION Q2
-- TPC-H/TPC-R Minimum Cost Supplier Query (Q2)
-- Stream 0, Query 2
-- Database -- <catalog>.<schema>

-- -------------------------------------------------------------------
-- For a given region, find the supplier who can supply a part
-- type and size at least cost.
-- -------------------------------------------------------------------
 
select [first 100]
      cast(s_acctbal as numeric(18,2)),
      s_name,
      n_name,
      p_partkey,
      p_mfgr,
      s_address,
      s_phone,
      s_comment
from
      tpch.part,
      tpch.supplier,
      tpch.partsupp,
      tpch.nation,
      tpch.region
where
      p_partkey = ps_partkey
      and s_suppkey = ps_suppkey
      and p_size = 15
      and p_type like '%BRASS'
      and s_nationkey = n_nationkey
      and n_regionkey = r_regionkey
      and r_name = 'EUROPE'
      and ps_supplycost = (
            select
                  min(ps_supplycost)
            from
                  tpch.partsupp,
                  tpch.supplier,
                  tpch.nation,
                  tpch.region
            where
                  p_partkey = ps_partkey
                  and s_suppkey = ps_suppkey
                  and s_nationkey = n_nationkey
                  and n_regionkey = r_regionkey
                  and r_name = 'EUROPE'
      )
order by
      s_acctbal desc,
      n_name,
      s_name,
      p_partkey;


-- ?SECTION Q3
-- TPC-H/TPC-R Shipping Priority Query (Q3)
-- Stream 0, Query 3
-- Database -- <catalog>.<schema>

-- -------------------------------------------------------------------
-- retrieves the shipping priority and potential revenue of orders
-- having the largest revenue among those that had not been shipped
-- as of a given date.
-- -------------------------------------------------------------------
 
select [first 10]
      l_orderkey,
      cast(sum(l_extendedprice*(1-l_discount)) as numeric(18,2)) as revenue,
      o_orderdate,
      o_shippriority
from
      tpch.customer,
      tpch.orders,
      tpch.lineitem
where
      c_mktsegment = 'BUILDING'
      and c_custkey = o_custkey
      and l_orderkey = o_orderkey
      and o_orderdate < date '1995-03-15'
      and l_shipdate > date '1995-03-15'
group by
      l_orderkey,
      o_orderdate,
      o_shippriority
order by
      revenue desc,
      o_orderdate;


-- ?SECTION Q4
-- TPC-H/TPC-R Order Priority Checking Query (Q4)
-- Stream 0, Query 4
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- counts the number of orders ordered in a given quarter of a given
-- year in which at least at least one lineitem was received later
-- than its committed date. The query lists the count of such orders
-- for each order priority sorted in ascending priority order.
-- ------------------------------------------------------------------
 
select
      o_orderpriority,
      count(*) as order_count
from
      tpch.orders
where
      o_orderdate >= date '1993-07-01'
      and o_orderdate < date '1993-07-01' + interval '3' month
      and exists (
            select
                  *
            from
                  tpch.lineitem
            where
                  l_orderkey = o_orderkey
                  and l_commitdate < l_receiptdate
      )
group by
      o_orderpriority
order by
      o_orderpriority;

-- ?SECTION Q5
-- TPC-H/TPC-R Local Supplier Volume Query (Q5)
-- Stream 0, Query 5
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- For each nation in a region, list the revenue resulting from
-- lineitem transactions in which the customer ordering parts and the
-- supplier filling them were both within that nation. Only parts
-- ordered in a given year are considered.  Ordered by revenue.
-- ------------------------------------------------------------------
 
select
      n_name,
      cast(sum(l_extendedprice * (1 - l_discount)) as numeric(18,2)) as revenue
from
      tpch.customer,
      tpch.orders,
      tpch.lineitem,
      tpch.supplier,
      tpch.nation,
      tpch.region
where
      c_custkey = o_custkey
      and l_orderkey = o_orderkey
      and l_suppkey = s_suppkey
      and c_nationkey = s_nationkey
      and s_nationkey = n_nationkey
      and n_regionkey = r_regionkey
      and r_name = 'ASIA'
      and o_orderdate >= date '1994-01-01'
      and o_orderdate < date '1994-01-01' + interval '1' year
group by
      n_name
order by
      revenue desc;

-- ?SECTION Q6
-- TPC-H/TPC-R Forecasting Revenue Change Query (Q6)
-- Stream 0, Query 6
-- Database -- <catalog>.<schema>

-- ----------------------------------------------------------------------
-- consider all lineitems shipped in a given year with discounts
-- within a specified range.  Lists the amount by which the total revenue
-- would have increased if these discounts had been eliminated.
-- ----------------------------------------------------------------------
 
select
      cast(sum(l_extendedprice*l_discount) as numeric(18,2)) as revenue
from
      tpch.lineitem
where
      l_shipdate >= date '1994-01-01'
      and l_shipdate < date '1994-01-01' + interval '1' year
      and l_discount between 0.06 - 0.01 and 0.06 + 0.01
      and l_quantity < 24;

-- ?SECTION Q7
-- TPC-H/TPC-R Volume Shipping Query (Q7)
-- Stream 0, Query 7
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- for two given nations, find the gross discounted revenues derived
-- from lineitems in which parts were shipped from a supplier in
-- either nation to a customer in the other nation during 1995 and
-- 1996.  Order by supplier nation, customer nation, and year.
-- ------------------------------------------------------------------
 
select
      supp_nation,
      cust_nation,
      l_year,
      cast(sum(volume) as numeric(18,2)) as revenue
from
      (
            select
                  n1.n_name as supp_nation,
                  n2.n_name as cust_nation,
                  extract(year from tpch.l_shipdate) as l_year,
                  l_extendedprice * (1 - l_discount) as volume
            from
                  tpch.supplier,
                  tpch.lineitem,
                  tpch.orders,
                  tpch.customer,
                  tpch.nation n1,
                  tpch.nation n2
            where
                  s_suppkey = l_suppkey
                  and o_orderkey = l_orderkey
                  and c_custkey = o_custkey
                  and s_nationkey = n1.n_nationkey
                  and c_nationkey = n2.n_nationkey
                  and (
                        (n1.n_name = 'FRANCE' and n2.n_name = 'GERMANY')
                        or (n1.n_name = 'GERMANY' and n2.n_name = 'FRANCE')
                  )
                  and l_shipdate between date '1995-01-01' and date '1996-12-31'
      ) as shipping
group by
      supp_nation,
      cust_nation,
      l_year
order by
      supp_nation,
      cust_nation,
      l_year;

-- ?SECTION Q8
-- TPC-H/TPC-R National Market Share Query (Q8)
-- Stream 0, Query 8
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- determines how the market share of a given nation in a given
-- region has changed over two years for a given part type. Market
-- share is the fraction of the revenue from products of a given type
-- that was generated by suppliers from the given nation.
-- ------------------------------------------------------------------
 
select
      o_year,
      cast(sum(case
            when nation = 'BRAZIL' then volume
            else 0
      end) / sum(volume) as numeric(18,3)) as mkt_share
from
      (
            select
                  extract(year from tpch.o_orderdate) as o_year,
                  l_extendedprice * (1 - l_discount) as volume,
                  n2.n_name as nation
            from
                  tpch.part,
                  tpch.supplier,
                  tpch.lineitem,
                  tpch.orders,
                  tpch.customer,
                  tpch.nation n1,
                  tpch.nation n2,
                  tpch.region
            where
                  p_partkey = l_partkey
                  and s_suppkey = l_suppkey
                  and l_orderkey = o_orderkey
                  and o_custkey = c_custkey
                  and c_nationkey = n1.n_nationkey
                  and n1.n_regionkey = r_regionkey
                  and r_name = 'AMERICA'
                  and s_nationkey = n2.n_nationkey
                  and o_orderdate between date '1995-01-01' and date '1996-12-31'
                  and p_type = 'ECONOMY ANODIZED STEEL'
      ) as all_nations
group by
      o_year
order by
      o_year;


-- ?SECTION Q9
-- TPC-H/TPC-R Product Type Profit Measure Query (Q9)
-- Stream 0, Query 9
-- Database -- <catalog>.<schema>

-- --------------------------------------------------------------------
-- determine how much profit is made on a line of
-- parts, broken out by supplier nation and year.
-- --------------------------------------------------------------------
 
select
      nation,
      o_year,
      cast(sum(amount) as numeric(18,2)) as sum_profit
from
      (
            select
                  n_name as nation,
                  extract(year from tpch.o_orderdate) as o_year,
                  l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount
            from
                  tpch.part,
                  tpch.supplier,
                  tpch.lineitem,
                  tpch.partsupp,
                  tpch.orders,
                  tpch.nation
            where
                  s_suppkey = l_suppkey
                  and ps_suppkey = l_suppkey
                  and ps_partkey = l_partkey
                  and p_partkey = l_partkey
                  and o_orderkey = l_orderkey
                  and s_nationkey = n_nationkey
                  and p_name like '%green%'
      ) as profit
group by
      nation,
      o_year
order by
      nation,
      o_year desc;


-- ?SECTION Q10
-- TPC-H/TPC-R Returned Item Reporting Query (Q10)
-- Stream 0, Query 10
-- Database -- <catalog>.<schema>

-------------------------------------------------------------------
-- identifies customers who might be having problems with the parts
-- that are shipped to them (returning them)
-------------------------------------------------------------------
 
select [first 20]
      c_custkey,
      c_name,
      cast(sum(l_extendedprice * (1 - l_discount)) as numeric(18,2)) as revenue,
      cast(c_acctbal as numeric(18,2)),
      n_name,
      c_address,
      c_phone,
      c_comment
from
      tpch.customer,
      tpch.orders,
      tpch.lineitem,
      tpch.nation
where
      c_custkey = o_custkey
      and l_orderkey = o_orderkey
      and o_orderdate >= date '1993-10-01'
      and o_orderdate < date '1993-10-01' + interval '3' month
      and l_returnflag = 'R'
      and c_nationkey = n_nationkey
group by
      c_custkey,
      c_name,
      c_acctbal,
      c_phone,
      n_name,
      c_address,
      c_comment
order by
      revenue desc;

-- ?SECTION Q11
-- TPC-H/TPC-R Important Stock Identification Query (Q11)
-- Stream 0, Query 11
-- Database -- <catalog>.<schema>

-- -------------------------------------------------------------------
-- find, for suppliers in a given nation, all the parts that represent
-- a significant percentage of the total value of all available parts
-- -------------------------------------------------------------------
 
select [last 0]
      ps_partkey,
      cast(sum(ps_supplycost * ps_availqty) as numeric(18,2)) as valuea
from
      tpch.partsupp,
      tpch.supplier,
      tpch.nation
where
      ps_suppkey = s_suppkey
      and s_nationkey = n_nationkey
      and n_name = 'GERMANY'
group by
      ps_partkey having
            sum(ps_supplycost * ps_availqty) > (
                  select
                        sum(ps_supplycost * ps_availqty) * 0.0001000000
                  from
                        tpch.partsupp,
                        tpch.supplier,
                        tpch.nation
                  where
                        ps_suppkey = s_suppkey
                        and s_nationkey = n_nationkey
                        and n_name = 'GERMANY'
            )
order by
      valuea desc;

-- ?SECTION Q12
-- TPC-H/TPC-R Shipping Modes and Order Priority Query (Q12)
-- Stream 0, Query 12
-- Database -- <catalog>.<schema>

-- -------------------------------------------------------------------
-- determines whether less expensive shipping modes are negatively
-- affecting critical priority orders
-- -------------------------------------------------------------------
 
select
      l_shipmode,
      sum(case
            when o_orderpriority = '1-URGENT'
                  or o_orderpriority = '2-HIGH'
                  then 1
            else 0
      end) as high_line_count,
      sum(case
            when o_orderpriority <> '1-URGENT'
                  and o_orderpriority <> '2-HIGH'
                  then 1
            else 0
      end) as low_line_count
from
      tpch.orders,
      tpch.lineitem
where
      o_orderkey = l_orderkey
      and l_shipmode in ('MAIL', 'SHIP')
      and l_commitdate < l_receiptdate
      and l_shipdate < l_commitdate
      and l_receiptdate >= date '1994-01-01'
      and l_receiptdate < date '1994-01-01' + interval '1' year
group by
      l_shipmode
order by
      l_shipmode;

-- ?SECTION Q13
-- TPC-H/TPC-R Customer Distribution Query (Q13)
-- Stream 0, Query 13
-- Database -- <catalog>.<schema>

-- ---------------------------------------------------------------------
-- determines the distribution of customers by the number of orders
-- they have made, including customers who have no record of orders,
-- past or present. Counts and reports how many customers have no
-- orders, how many have 1, 2, 3, etc. A check is made to ensure that
-- the orders counted do not fall into one of several special categories
-- of orders. Special categories are identified in the order comment
-- column by looking for a particular pattern.
-- ---------------------------------------------------------------------
 
select
      c_count,
      count(*) as custdist
from
      (
            select
                  c_custkey,
                  count(o_orderkey)
            from
                  tpch.customer left outer join tpch.orders on
                        c_custkey = o_custkey
                        and o_comment not like '%special%requests%'
            group by
                  c_custkey
      ) as c_orders (c_custkey, c_count)
group by
      c_count
order by
      custdist desc,
      c_count desc;


-- ?SECTION Q14
-- TPC-H/TPC-R Promotion Effect Query (Q14)
-- Stream 0, Query 14
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- determine what % of revenue in a given year & month was derived
-- from promotional parts shipped in a given month.
-- ------------------------------------------------------------------
 
select
      cast( (100.00 * sum(case
            when p_type like 'PROMO%'
                  then l_extendedprice * (1 - l_discount)
            else 0
      end) / sum(l_extendedprice * (1 - l_discount)) 
      ) as numeric(18,3)) as promo_revenue
from
      tpch.lineitem,
      tpch.part
where
      l_partkey = p_partkey
      and l_shipdate >= date '1995-09-01'
      and l_shipdate < date '1995-09-01' + interval '1' month;

-- ?SECTION Q15
-- TPC-H/TPC-R Top Supplier Query (Q15)
-- Stream 0, Query 15
-- Database -- <catalog>.<schema>

-- ------------------------------------------------------------------
-- determines supplier who contributed most to the overall revenue   
-- for parts shipped during a given quarter of a given year.         
-- ------------------------------------------------------------------

-- Fix -- cast predicate and subquery to ensure match
-- Fix -- replaced view with in-line SQL
 
select
      s_suppkey,
      s_name,
      s_address,
      s_phone,
      cast(total_revenue as numeric(18,2))
from
      tpch.supplier,
      (
      select
            l_suppkey,
            sum(l_extendedprice * (1 - l_discount))
      from
            tpch.lineitem
      where
            l_shipdate >= date '1996-01-01'
            and l_shipdate < date '1996-01-01' + interval '3' month
      group by
            l_suppkey
      ) as v(supplier_no, total_revenue)
where
      s_suppkey = supplier_no
      and cast((total_revenue + 0.005) as numeric(18,2)) = (
            select
                  cast((max(total_revenue) + 0.005) as numeric(18,2))
            from
            (
            select
                  l_suppkey,
                  sum(l_extendedprice * (1 - l_discount))
            from
                  tpch.lineitem
            where
                  l_shipdate >= date '1996-01-01'
                  and l_shipdate < date '1996-01-01' + interval '3' month
            group by
                  l_suppkey
            ) as v1(supplier_no, total_revenue)
      )
order by
      s_suppkey;


-- ?SECTION Q16
-- TPC-H/TPC-R Parts/Supplier Relationship Query (Q16)
-- Stream 0, Query 16
-- Database -- <catalog>.<schema>

-- -----------------------------------------------------------------
-- count the number of suppliers who can supply parts that satisfy a
-- particular customer's requirements
-- -----------------------------------------------------------------
 
select [last 0]
      p_brand,
      p_type,
      p_size,
      count(distinct ps_suppkey) as supplier_cnt
from
      tpch.partsupp,
      tpch.part
where
      p_partkey = ps_partkey
      and p_brand <> 'Brand#45'
      and p_type not like 'MEDIUM POLISHED%'
      and p_size in (49, 14, 23, 45, 19, 3, 36, 9)
      and ps_suppkey not in (
            select
                  s_suppkey
            from
                  tpch.supplier
            where
                  s_comment like '%Customer%Complaints%'
      )
group by
      p_brand,
      p_type,
      p_size
order by
      supplier_cnt desc,
      p_brand,
      p_type,
      p_size;

-- ?SECTION Q19
-- TPC-H/TPC-R Discounted Revenue Query (Q19)
-- Stream 0, Query 19
-- Database -- <catalog>.<schema>

-- ----------------------------------------------------------------
-- find gross discounted revenue for all orders for three different
-- types of parts that were shipped by air or delivered in person
-- ----------------------------------------------------------------
 
select
      cast (sum(l_extendedprice* (1 - l_discount)) as numeric(18,4)) as revenue
from
      tpch.lineitem,
      tpch.part
where
      (
            p_partkey = l_partkey
            and p_brand = 'Brand#12'
            and p_container in ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')
            and l_quantity >= 1 and l_quantity <= 1 + 10
            and p_size between 1 and 5
            and l_shipmode in ('AIR', 'AIR REG')
            and l_shipinstruct = 'DELIVER IN PERSON'
      )
      or
      (
            p_partkey = l_partkey
            and p_brand = 'Brand#23'
            and p_container in ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK')
            and l_quantity >= 10 and l_quantity <= 10 + 10
            and p_size between 1 and 10
            and l_shipmode in ('AIR', 'AIR REG')
            and l_shipinstruct = 'DELIVER IN PERSON'
      )
      or
      (
            p_partkey = l_partkey
            and p_brand = 'Brand#34'
            and p_container in ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG')
            and l_quantity >= 20 and l_quantity <= 20 + 10
            and p_size between 1 and 15
            and l_shipmode in ('AIR', 'AIR REG')
            and l_shipinstruct = 'DELIVER IN PERSON'
      );
